############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

# [[main]]
# name = "Elements"
# pageRef = "/elements"
# weight = 3

[[main]]
weight = 7
name = "Services"

[[main]]
# parent = "Pages"
name = "Blog"
pageRef = "/blog"
weight = 3

[[main]]
name = "Docs"
weight = 4
identifier = "docs"
url = "https://snigdhaos.org/documentation/"
# pre = "images/book-solid.svg"
target = "_blank"

# [[main]]
# # parent = "Pages"
# name = "Contact"
# pageRef = "/contact"
# weight = 5

[[main]]
parent = "Extra"
name = "Authors"
pageRef = "/authors"
weight = 6

[[main]]
parent = "Services"
name = "Cloud"
weight = 4
identifier = "cloud"
url = "https://cloud.snigdhaos.org/"
# pre = "images/book-solid.svg"
target = "_blank"

[[main]]
parent = "Services"
name = "Forum"
weight = 4
identifier = "forum"
url = "https://forum.snigdhaos.org/"
# pre = "images/book-solid.svg"
target = "_blank"

# footer menu
[[footer]]
name = "Cloud"
weight = 1
identifier = "cloud"
url = "https://cloud.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Forum"
weight = 2
identifier = "forum"
url = "https://forum.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Status"
weight = 3
identifier = "status"
url = "https://snigdha-os.github.io/snigdhaos-status/"
target = "_blank"

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 4
