############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

# [[main]]
# name = "Elements"
# pageRef = "/elements"
# weight = 3

# [[main]]
# weight = 4
# name = "Pages"

[[main]]
# parent = "Pages"
name = "Blog"
pageRef = "/blog"
weight = 3

[[main]]
# parent = "Pages"
name = "Contact"
pageRef = "/contact"
weight = 4

[[main]]
# parent = "Pages"
name = "Authors"
pageRef = "/authors"
weight = 5

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
