############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3

[[main]]
name = "Docs"
weight = 4
identifier = "docs"
url = "https://snigdhaos.org/documentation/"
target = "_blank"

[[main]]
name = "Get Started"
pageRef = "/get-started"
weight = 5

# footer menu
[[footer]]
name = "Cloud"
weight = 1
identifier = "cloud"
url = "https://cloud.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Forum"
weight = 2
identifier = "forum"
url = "https://forum.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Uptime"
weight = 3
identifier = "uptime"
url = "https://uptime.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Tools"
weight = 4
identifier = "tools"
url = "https://tools.snigdhaos.org/"
target = "_blank"

[[footer]]
name = "Status"
weight = 5
identifier = "status"
url = "https://snigdha-os.github.io/snigdhaos-status/"
target = "_blank"

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 6
